name: Hotel-Booking-WebAPP 

on:
  push:
    branches: [AIRBNB]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Hotel-Booking Project
        run:  CI=false npm run build